### PR TITLE
added panful.com

### PR DESCRIPTION
**Pull request by goethewins**
Fastest way to Buy Bitcoins instantly with PayPal, Western Union and bank transfers. Peer to Peer exchange

### CODE REVIEW

**Comment by slick2** [comment]
is this panful.com or paxful.com ? when I tried the link there is a privacy error, kindly fix those. 

thanks.

**Comment by goethewins** [comment]
paxful.com
changed it to http://  for the landing page. 

thank you so much and very sorry for the trouble.

**Comment by goethewins** [comment]
paxful.com
changed it to http:// for the landing page.

thank you so much and very sorry for the trouble.

**Comment by goethewins** [comment]
wow , thank you so much!!!!!

you guys rock!!!

Thank you Johnathan!

-Ray

**Comment by goethewins** [comment]
Have a serious IP copyright conflict issue, entirely my own fault. sorry

Could you merge this please
https://github.com/jonwaller/howtobuybitcoinsinfo-website/pull/240

**Comment by goethewins** [comment]
Hi, how can we sponsor the site? Like luxstack?
Cost?

Want to do it asap.

**Pull request merged**
